"""Rebuild the two local Parsons joins using Shapely 2."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent/'node_modules/road-geometry-tools'))
from shapely.geometry import LineString,Point
from shapely.ops import unary_union
root=Path(__file__).resolve().parent.parent
data=json.loads((root/'Research/historic-roads/west-parsons-input.json').read_text())
existing=unary_union([LineString(r['points']).buffer(r.get('width',6)/2,quad_segs=5) for r in data['roads']])
result=[]
for join in data['joins']:
    # Merge into the actual lane bends, then soften the exposed corners.
    region=Point(join['junctionOrigin']).buffer(24,quad_segs=24)
    road=next(r for r in data['roads'] if join['name']==r['name']+' Parsons junction')
    endpoint=road['points'][0 if road['name']=='Northern estate boundary' else -1]
    connector=LineString([endpoint,join['junctionOrigin']]).buffer(road['width']/2,quad_segs=12)
    full=unary_union([existing,connector]).buffer(5,quad_segs=24).buffer(-5,quad_segs=24)
    for geom,suffix,surface in [(full.intersection(region),'','junction'),(full.buffer(.6,quad_segs=12).difference(full).intersection(region),' border','junction edge')]:
        polygons=[geom] if geom.geom_type=='Polygon' else list(geom.geoms)
        for i,p in enumerate(polygons):
            if p.area<.001: continue
            result.append(dict(name=join['name']+suffix+(' '+str(i) if i else ''),surface=surface,points=list(p.exterior.coords)[:-1],holes=[list(h.coords)[:-1] for h in p.interiors]))
(root/'Browser/dist/west-parsons-junctions.mjs').write_text('// Generated by Browser/build-west-parsons-junctions.py. Local merged road mouths.\nexport const WEST_PARSONS_JUNCTIONS=Object.freeze('+json.dumps(result,separators=(',',':'))+');\n')
print('Generated',len(result),'local road surfaces')



