"""Rebuild the marked Southern estate drive / Parsons Lane junction."""
import json
import subprocess
import sys
from pathlib import Path

browser = Path(__file__).resolve().parent
sys.path.insert(0, str(browser / 'node_modules/road-geometry-tools'))
from shapely.geometry import LineString, Point
from shapely.ops import unary_union

# Read the current approved traces so regenerating cannot silently retain an
# old road alignment. The untrimmed drive supplies the missing through link.
source = """
import {HISTORIC_ROAD_TRACES} from './dist/historic-road-layout.mjs';
import {SHARED_HISTORIC_LANES} from './dist/historic-road-clearance.mjs';
console.log(JSON.stringify({drive:HISTORIC_ROAD_TRACES.find(r=>r.name==='Southern estate drive'),lane:SHARED_HISTORIC_LANES.find(r=>r.name==='Parsons Lane (North)')}));
"""
data = json.loads(subprocess.check_output(['node', '--input-type=module', '-e', source], cwd=browser, text=True))
origin = data['lane']['points'][0]
region = Point(origin).buffer(24, quad_segs=24)
roads = unary_union([LineString(data[key]['points']).buffer(3, quad_segs=5) for key in ['drive', 'lane']])
# Round the two inside corners while retaining the through-road's outside
# verge. Only the exposed edges receive kerbs; the three mouths stay open.
asphalt = roads.buffer(5, quad_segs=24).buffer(-5, quad_segs=24)
border = asphalt.buffer(.6, quad_segs=12).difference(asphalt)
surfaces = []
for shape, suffix, surface in [(asphalt, '', 'junction'), (border, ' border', 'junction edge')]:
    clipped = shape.intersection(region)
    pieces = [clipped] if clipped.geom_type == 'Polygon' else list(clipped.geoms)
    for i, polygon in enumerate(pieces):
        if polygon.area < .001:
            continue
        surfaces.append(dict(name='Southern estate drive Parsons junction' + suffix + (f' {i}' if i else ''), surface=surface,
                             points=list(polygon.exterior.coords)[:-1], holes=[list(h.coords)[:-1] for h in polygon.interiors]))
output = '// Generated by Browser/build-southern-junction.py. Local merged road mouth.\n'
output += 'export const SOUTHERN_DRIVE_JUNCTION=Object.freeze(' + json.dumps(surfaces, separators=(',', ':')) + ');\n'
(browser / 'dist/southern-drive-junction.mjs').write_text(output)
print(f'Generated {len(surfaces)} southern junction surfaces')
