"""Rebuild the merged rear-road outlines (Python with Shapely 2).
Input stores the annotated traces and exact wall outlines from the approved scene.
Browser rendering needs no Python or polygon-boolean runtime dependency.
"""
import json, sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent/'artifacts/rear-road-tools'))
from shapely.geometry import Polygon, LineString
from shapely.ops import unary_union
root=Path(__file__).resolve().parent.parent
source=json.loads((root/'Research/historic-roads/annexe-rear-network-input.json').read_text())
# Smooth interpolating curves retain the annotated branches and common nodes.
def smooth(points):
    out=[]
    for i in range(len(points)-1):
        a,b,c,d=points[max(0,i-1)],points[i],points[i+1],points[min(i+2,len(points)-1)]
        for step in range(16):
            t=step/16
            out.append([.5*(2*b[k]+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t*t+(-a[k]+3*b[k]-3*c[k]+d[k])*t*t*t) for k in range(2)])
    return out+[points[-1]]
traces=[smooth(p) for p in source['routes']]
road=unary_union([LineString(p).buffer(source['width']/2,quad_segs=12) for p in traces])
# Remove internal corners at branch mouths while keeping the carriageway width.
road=road.buffer(2,quad_segs=12).buffer(-2,quad_segs=12)
walls=unary_union([Polygon(w['points']) for w in source['walls']])
shared=unary_union([LineString(p['points']).buffer(p.get('width',6)/2,quad_segs=5) for p in source['shared']])
shared_outer=unary_union([LineString(p['points']).buffer(p.get('width',6)/2+.6,quad_segs=5) for p in source['shared']])
existing_paving=[Polygon(p['points'],p.get('holes',[])) for p in source['existingPaving'] if p.get('surface')!='junction edge']
existing_edges=[Polygon(p['points'],p.get('holes',[])) for p in source['existingPaving']]
shared=unary_union([shared,*existing_paving])
shared_outer=unary_union([shared_outer,*existing_edges])
full=unary_union([road,Polygon(source['court'])]).difference(walls)
asphalt=full.difference(shared)
# Border only the exposed lawn edge, never a wall or an existing road mouth.
border=full.buffer(.6,quad_segs=12).difference(full).difference(walls.buffer(.02)).difference(shared_outer)
def areas(g,surface):
    polygons=[g] if g.geom_type=='Polygon' else list(g.geoms)
    return [dict(name='Annexe rear network '+surface+' '+str(i+1),surface='junction' if surface=='asphalt' else 'junction edge',points=[list(p) for p in v.exterior.coords[:-1]],holes=[[list(p) for p in ring.coords[:-1]] for ring in v.interiors]) for i,v in enumerate(polygons) if v.area>.005]
# Serialize shared ring vertices without independent rounding at junctions.
text=json.dumps(areas(asphalt,'asphalt')+areas(border,'border'),separators=(',',':'))
(root/'Browser/dist/annexe-rear-roads.mjs').write_text('// Generated by Browser/build-annexe-rear-roads.py from the owner-marked reference.\n// One merged asphalt region; kerbs follow only exposed lawn boundaries.\nexport const ANNEXE_REAR_SURFACES=Object.freeze('+text+');\n')
assert asphalt.is_valid and border.is_valid
assert asphalt.intersection(walls).area < 1e-8
assert asphalt.intersection(shared).area < 1e-8
assert asphalt.intersection(border).area < 1e-8
print('Merged asphalt area:',round(asphalt.area,2),'border area:',round(border.area,2),'wall overlap:',asphalt.intersection(walls).area,'shared asphalt overlap:',asphalt.intersection(shared).area)
