import assert from 'node:assert/strict';
import * as THREE from './dist/vendor/three.module.js';
import {createWalker,exteriorObstacles} from './dist/explore-controls.mjs';
import {createEscapeExterior} from './dist/escape-exterior.mjs';
import {EAST_PHOTO_VIEW} from './dist/east-photo-detail.mjs';
const camera=new THREE.PerspectiveCamera(),walker=createWalker(camera);
walker.keys.add('KeyW');walker.update(.1);assert.equal(camera.position.z,39.5);
walker.keys.add('KeyD');const before=camera.position.clone();walker.update(.1);assert(Math.abs(camera.position.distanceTo(before)-.5)<1e-10,'diagonal speed stays normalized');
walker.reset();walker.look(-Math.PI/2/.002,0);walker.keys.add('KeyW');walker.update(.1);assert(camera.position.x<-.49,'movement follows mouse yaw');
walker.look(0,1e6);assert.equal(camera.rotation.x,-1.45,'mouse pitch cannot flip the camera');
walker.setView(EAST_PHOTO_VIEW);
const photoForward=new THREE.Vector3();camera.getWorldDirection(photoForward);
const photoBefore=camera.position.clone();walker.keys.add('KeyW');walker.update(.1);
assert(camera.position.clone().sub(photoBefore).dot(photoForward)>0,'walking from the photo preset follows its viewing direction');
walker.look(0,0);assert(Math.abs(camera.rotation.y)>0.1,'first mouse movement must retain the preset direction');
walker.reset();assert.equal(camera.fov,50,'return to entrance restores the original field of view');
globalThis.document={createElement:()=>({getContext:()=>({fillRect(){}})})};
const exterior=createEscapeExterior(THREE,16/9),obstacles=exteriorObstacles(THREE,exterior.model),walk=createWalker(exterior.camera,obstacles);
walk.keys.add('KeyW');for(let i=0;i<100;i++)walk.update(.1);
assert(exterior.camera.position.z>23,'walking toward the entrance stops at its steps');
walk.keys.add('KeyD');for(let i=0;i<10;i++)walk.update(.1);
assert(exterior.camera.position.x>1,'the player can slide sideways along an obstacle');
walk.reset();assert.equal(exterior.camera.position.z,40);assert.equal(walk.keys.size,0);
walk.keys.add('KeyW');walk.update(60);assert(exterior.camera.position.z>=39.5,'long frame cannot teleport the player');
walk.reset();exterior.camera.position.set(76,1.8,28);walk.keys.add('KeyW');
for(let i=0;i<80;i++)walk.update(.1);
assert(exterior.camera.position.z<-10,'the ground-floor bridge passage must lead all the way into the courtyard');
walk.keys.clear();walk.keys.add('KeyS');for(let i=0;i<80;i++)walk.update(.1);
assert(exterior.camera.position.z>27,'the courtyard passage is traversable back to the front lawn');
// The garden and both stair structures leave a continuous route along x=9.
walk.setView({position:[9,1.8,-43],target:[9,1.8,0]});
walk.keys.add('KeyW');for(let i=0;i<74;i++)walk.update(.1);
assert(exterior.camera.position.z>-7,'inner courtyard remains reachable from the rear road beside the raised garden');
walk.keys.clear();walk.keys.add('KeyS');for(let i=0;i<74;i++)walk.update(.1);
assert(exterior.camera.position.z<-42,'the same inner-court route remains open in reverse');
walk.setView({position:[-48,1.8,-29],target:[-48,1.8,5]});
walk.keys.add('KeyW');for(let i=0;i<56;i++)walk.update(.1);
assert(exterior.camera.position.z> -2,'west courtyard remains accessible to the entrance apron');
walk.setView({position:[-58.4,1.8,-20],target:[-58.4,1.8,5]});
walk.keys.add('KeyW');for(let i=0;i<55;i++)walk.update(.1);
assert(exterior.camera.position.z<1,'walking must stop at the new polygonal bay');
walk.setView({position:[-60,1.8,44],target:[-60,1.8,20]});
walk.keys.add('KeyW');for(let i=0;i<60;i++)walk.update(.1);
assert(exterior.camera.position.z>25,'west front square pavilion must block walking through its facade');
walk.setView({position:[-49,1.8,43],target:[-35,1.8,43]});
walk.keys.add('KeyW');for(let i=0;i<40;i++)walk.update(.1);
assert(exterior.camera.position.x<-45.4,'low glazed extension must block walking through its side');
delete globalThis.document;
console.log('PASS: exterior WASD, normalized diagonals, mouse-relative movement, pitch limits, building collisions, wall sliding, reset and stalled frames.');
