import assert from 'node:assert/strict';
import * as THREE from './dist/vendor/three.module.js';
import {createWalker,exteriorObstacles} from './dist/explore-controls.mjs';
import {createEscapeExterior} from './dist/escape-exterior.mjs';
const camera=new THREE.PerspectiveCamera(),walker=createWalker(camera);
walker.keys.add('KeyW');walker.update(.1);assert.equal(camera.position.z,39.5);
walker.keys.add('KeyD');const before=camera.position.clone();walker.update(.1);assert(Math.abs(camera.position.distanceTo(before)-.5)<1e-10,'diagonal speed stays normalized');
walker.reset();walker.look(-Math.PI/2/.002,0);walker.keys.add('KeyW');walker.update(.1);assert(camera.position.x<-.49,'movement follows mouse yaw');
walker.look(0,1e6);assert.equal(camera.rotation.x,-1.45,'mouse pitch cannot flip the camera');
globalThis.document={createElement:()=>({getContext:()=>({fillRect(){}})})};
const exterior=createEscapeExterior(THREE,16/9),obstacles=exteriorObstacles(THREE,exterior.model),walk=createWalker(exterior.camera,obstacles);
walk.keys.add('KeyW');for(let i=0;i<100;i++)walk.update(.1);
assert(exterior.camera.position.z>23,'walking toward the entrance stops at its steps');
walk.keys.add('KeyD');for(let i=0;i<10;i++)walk.update(.1);
assert(exterior.camera.position.x>1,'the player can slide sideways along an obstacle');
walk.reset();assert.equal(exterior.camera.position.z,40);assert.equal(walk.keys.size,0);
walk.keys.add('KeyW');walk.update(60);assert(exterior.camera.position.z>=39.5,'long frame cannot teleport the player');
walk.reset();exterior.camera.position.set(76,1.8,28);walk.keys.add('KeyW');
for(let i=0;i<80;i++)walk.update(.1);
assert(exterior.camera.position.z<-10,'the ground-floor bridge passage must lead all the way into the courtyard');
walk.keys.clear();walk.keys.add('KeyS');for(let i=0;i<80;i++)walk.update(.1);
assert(exterior.camera.position.z>27,'the courtyard passage is traversable back to the front lawn');
delete globalThis.document;
console.log('PASS: exterior WASD, normalized diagonals, mouse-relative movement, pitch limits, building collisions, wall sliding, reset and stalled frames.');
