import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import * as THREE from '../dist/vendor/three.module.js';
import {createEscapeExterior} from '../dist/escape-exterior.mjs';
import {jarmanProtected} from './jarman-scope.mjs';
const encode=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const absolute=(s,base,override={})=>s.replace(/from '(\.[^']+)'/g,(_,p)=>"from '"+(override[p]??new URL(p,base).href)+"'");
const frontURL=new URL('../dist/annexe-outer-front.mjs',import.meta.url);
const oldFront=encode(absolute(execFileSync('git',['show','HEAD:Browser/dist/annexe-outer-front.mjs'],{encoding:'utf8',windowsHide:true}),frontURL));
const annexeURL=new URL('../dist/annexe.mjs',import.meta.url);
const oldAnnexe=encode(absolute(readFileSync(annexeURL,'utf8'),annexeURL,{'./annexe-outer-front.mjs':oldFront}));
const exteriorURL=new URL('../dist/escape-exterior.mjs',import.meta.url);
const oldExterior=await import(encode(absolute(readFileSync(exteriorURL,'utf8'),exteriorURL,{'./annexe.mjs':oldAnnexe})));
export const legacyExterior=oldExterior.createEscapeExterior;
globalThis.document={createElement:()=>({getContext:()=>({fillRect(){},clearRect(){},fillText(){},strokeText(){},measureText(t){return {width:t.length*16}}})})};
const old=legacyExterior(THREE,16/9),now=createEscapeExterior(THREE,16/9);
console.log('OLD',jarmanProtected(THREE,old.model),'NEW',jarmanProtected(THREE,now.model));
const counts=root=>{const counts={};root.traverse(o=>{if(o.isMesh){for(let p=o;p;p=p.parent)if(p.name==='West court front elevation')return;const name=o.name+' @ '+o.parent.name;counts[name]=(counts[name]??0)+(o.isInstancedMesh?o.count:1);}});return counts;};
const b=counts(old.model),a=counts(now.model);for(const k of new Set([...Object.keys(a),...Object.keys(b)]))if(a[k]!==b[k])console.log(k,b[k],a[k]);
